In [9]:
#convention is to load pandas as pd.
import pandas as pd
#import numpy as np

#for visualisations,seaborn library is used for statistical graphs
import seaborn as sns

#matplotlib creates plots/graphs.
import matplotlib.pyplot as plt

In [10]:
#import the data
data =pd.read_csv('sales_data1.csv', encoding = 'latin1')
data.head(2)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ONLINE ORDERS,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30.0,95.70,2,2871.0,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34.0,81.35,5,2765.9,05/07/2003 00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small

In [11]:
data.shape

(2823, 25)

In [12]:
data.dtypes

ORDERNUMBER           int64
QUANTITYORDERED     float64
PRICEEACH           float64
ONLINE ORDERS         int64
SALES               float64
ORDERDATE               str
STATUS                  str
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE             str
MSRP                  int64
PRODUCTCODE             str
CUSTOMERNAME            str
PHONE                   str
ADDRESSLINE1            str
ADDRESSLINE2            str
CITY                    str
STATE                   str
POSTALCODE              str
COUNTRY                 str
TERRITORY               str
CONTACTLASTNAME         str
CONTACTFIRSTNAME        str
DEALSIZE                str
dtype: object

In [13]:
#1. clean up the columns
data.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        2
PRICEEACH              0
ONLINE ORDERS          0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [16]:
data.fillna("")
data.head(3)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ONLINE ORDERS,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30.0,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,,NYC,NY,10022,USA,,Yu,Kwai,Small
1,10121,34.0,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,,Reims,,51100,France,EMEA,Henriot,Paul,Small
2,10134,41.0,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,,Paris,,75508,France,EMEA,Da Cunha,Daniel,Medium

In [18]:
#Create a line graph
data['Sales'].plot(x='Year_ID'. kind = 'line', markers='0', figsize=(8,5),title='Sales Over Time')

SyntaxError: invalid syntax (919433050.py, line 2)