In [62]:
pip install pandas

#Import Panda Library
#import pandas as pd

#impoprt the statistical library
#import numpy as np

SyntaxError: invalid syntax (3546230772.py, line 1)

In [ ]:
pip install numpy

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

import numpy as np

In [ ]:
#call the Dataframe - 'df'
df= pd.read_csv ('sales_null.csv', encoding = 'latin 1')
#.head reduces the output
df.head(1)

In [ ]:
df.head(2)

In [ ]:
#to display the last row of data
df.tail(1)

In [ ]:
#to list the names of columns & types of data to work with
df.columns
df.dtypes

In [ ]:
#1 cleaning data
#see what columns have null values
df.isnull().sum()

In [63]:
#gives the number of rows & columns of data
df.shape

(100, 13)

In [64]:
df.head(1)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50

Have to Clean data first

In [65]:
#Option 1. Use 'dropna' method to drop values in each row.
#Problem in slose al lot of data
df_nonNAN = df.dropna()
df_nonNAN.head(3)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50
88,Middle East and North Africa,Kuwait,Fruits,Online,M,4/30/2012,513417565.00,5/18/2012,522.00,9.33,6.92,4870.26,3612.24
89,Europe,Slovenia,Beverages,Offline,C,10/23/2016,345718562.00,11/25/2016,4660.00,47.45,31.79,221117.00,148141.40

In [66]:
#Option 2 , use 'fillna' method replace missing data with another value
#Fillna (0) =replaces with 0

filled_df = df.fillna(0)
filled_df.head(3)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.00,9/15/2012,2804.00,205.70,117.11,0.00,328376.44
2,Europe,Russia,Office Supplies,Offline,L,05/02/2014,341417157.00,05/08/2014,1779.00,651.21,524.96,0.00,933903.84

In [67]:
#Option 3, use 'fill(mean)' method with the AVERAGE (mean) or middle (median).
#Thsi is one column exmaple with total Revenue.
filled_df ['Total Revenue'] = df['Total Revenue'].fillna(df['Total Revenue'].mean())
filled_df.head(3)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.00,9/15/2012,2804.00,205.70,117.11,1384023.83,328376.44
2,Europe,Russia,Office Supplies,Offline,L,05/02/2014,341417157.00,05/08/2014,1779.00,651.21,524.96,1384023.83,933903.84

In [68]:
#Option 4 is to fill all null VALUES with the last value.
fill_last = df.ffill()
fill_last.head(3)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.00,9/15/2012,2804.00,205.70,117.11,2533654.00,328376.44
2,Europe,Russia,Office Supplies,Offline,L,05/02/2014,341417157.00,05/08/2014,1779.00,651.21,524.96,2533654.00,933903.84

In [69]:
#to see the stats of the columns - only floating or int are displayed.
filled_df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
count,100.00,100.00,100.00,100.00,100.00,100.00
mean,506160522.78,840.26,276.76,191.05,1384023.83,931805.70
std,284890664.18,2219.26,235.59,188.21,1437540.08,1083938.25
min,0.00,0.00,9.33,6.92,4870.26,3612.24
25%,247387599.75,0.00,81.73,35.84,311831.19,168868.03
50%,513147842.00,0.00,179.88,107.28,813382.81,363566.39
75%,757012033.00,0.00,437.20,263.33,2058107.70,1613869.72
max,994022214.00,9925.00,668.27,524.96,5997054.98,4509793.96

In [70]:
# change all floating numbers to decimal to 2 places.
pd.options.display.float_format = '{:.2f}'.format
filled_df.head(1)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.00,6/27/2010,9925.00,255.28,159.42,2533654.00,1582243.50

In [71]:
#convert floating point numbers into Integers.  
filled_df['Units Sold'] = filled_df['Units Sold'].astype(int)
filled_df['Order ID'] = filled_df['Order ID'].astype(int)

#to display the datatypes
display(filled_df.dtypes)

Region                str
Country               str
Item Type             str
Sales Channel         str
Order Priority        str
Order Date            str
Order ID            int64
Ship Date             str
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
dtype: object

In [72]:
filled_df.head(2)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,1384023.83,328376.44

In [73]:
#creat a calculated column called 'Total Profit'
filled_df['Total Profit'] = filled_df['Total Revenue'] - filled_df['Total Cost']
filled_df.head(1)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50

In [74]:
#To find the total profit for all the data.
Total_Profit = filled_df['Total Profit'].sum()
print('Total Profit for all the Regions is:', Total_Profit)

Total Profit for all the Regions is: 45221812.74263158

In [75]:
#to select data rows.  Many methods to use.
Grenada = filled_df[filled_df['Country'] == 'Grenada']
Grenada

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,1384023.83,328376.44,1055647.39